project: 
  name: ~
db:
  host: ~
  user: ~
  port: ~
  password: ~
  table: ~
jwt:
  secret: ~
firbase:
  buket_storage: ~
logging: 
  level: ~
telegram: 
  active: False
  token: ~
  admin_id: ~
flask:
  host: ~
  port: ~