project:
    name: ~
db:
    host: ~
    user: ~
    port: ~
    password: ~
    table: ~
jwt:
    secret: ~
code:
  minuts_valid: ~
firebase:
    bucket: ~
logging:
    level: ~
cron:
    active: ~
    test_enabled: ~
brevo:
    api_key: ~
    sender: ~
telegram:
    active: False
    token: ~
    admin_id: ~
flask:
    host: ~
    port: ~
