project: 
  name: ~
db:
  host: ~
  user: ~
  port: ~
  password: ~
  table: ~
jwt:
  secret: ~
firebase:
  bucket: ~
logging: 
  level: ~
cron:
  active: ~
  test_enabled: ~
telegram: 
  active: False
  token: ~
  admin_id: ~
flask:
  host: ~
  port: ~