version: '3.1'
services:
    server:
        build: ./
        command: >
            bash -c "migration.sh
            python3 -m gunicorn --workers 4 --bind 0.0.0.0:5000 app:app"
        ports:
            - 5000:5000
        depends_on:
            - postgres
        volumes:
            - .:/app
        environment:
            - FLASK_APP=app.py
            - FLASK_ENV=development
        networks:
            - gap-network

    postgres:
        image: postgres:13-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=graph-a-pet
        networks:
            - gap-network
volumes:
  postgres_data:

networks:
    gap-network: