version: '3.1'
services:
    server:
        build: ./app
        command: python3 -m gunicorn --workers 4 --bind 0.0.0.0:5000 app:app
        ports:
            - 5000:5000
        volumes:
            - ./app:/app
        environment:
            - FLASK_APP=project/__init__.py
            - FLASK_ENV=development