version: '3.1'
services:
    server:
        build: ./
        command: python3 -m gunicorn --workers 4 --bind 0.0.0.0:5000 app:app
        ports:
            - 5000:5000
        volumes:
            - .:/app
        environment:
            - FLASK_APP=app.py
            - FLASK_ENV=development

    db:
        image: postgres:13-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=pet-finder