"""remove alias column

Revision ID: 0365689ed169
Revises: 4825a71b7e18
Create Date: 2022-07-15 10:08:03.108638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0365689ed169'
down_revision = '4825a71b7e18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatments', 'alias')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatments', sa.Column('alias', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
