"""deleted pet_body

Revision ID: 0783f250015e
Revises: 0c72b44a2ddd
Create Date: 2025-08-03 15:35:20.507122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0783f250015e'
down_revision = '0c72b44a2ddd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Rimuove il vincolo di foreign key
    op.drop_constraint('pets_body_id_fkey', 'pets', schema='graph_a_pet', type_='foreignkey')
    
    # Rimuove la colonna `body_id` dalla tabella `pets`
    op.drop_column('pets', 'body_id', schema='graph_a_pet')

    # Elimina la tabella `pet_bodies`
    op.drop_table('pet_bodies', schema='graph_a_pet')

    # Aggiunge le nuove colonne
    op.add_column('pets', sa.Column('coat_length', sa.Enum('SHORT', 'MEDIUM', 'LENGHT', 'HAIRLESS', name='coatlength'), nullable=True), schema='graph_a_pet')
    op.add_column('pets', sa.Column('breed', sa.String(), nullable=True), schema='graph_a_pet')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('body_id', sa.VARCHAR(), autoincrement=False, nullable=True), schema='graph_a_pet')
    op.drop_column('pets', 'breed', schema='graph_a_pet')
    op.drop_column('pets', 'coat_length', schema='graph_a_pet')
    op.create_table('pet_bodies',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('family', postgresql.ENUM('REPTILE', 'CANINE', 'FELINE', 'BIRDS', 'FISH', name='petfamily'), autoincrement=False, nullable=True),
    sa.Column('breed', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('coat_length', postgresql.ENUM('SHORT', 'MEDIUM', 'LENGHT', 'HAIRLESS', name='coatlength'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pet_bodies_pkey'),
    schema='graph_a_pet'
    )
    # ### end Alembic commands ###
