"""added report date

Revision ID: 0c72b44a2ddd
Revises: f676da2034f6
Create Date: 2025-07-26 21:36:04.462063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c72b44a2ddd'
down_revision = 'f676da2034f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('date', sa.DateTime(), nullable=True), schema='graph_a_pet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'date', schema='graph_a_pet')
    # ### end Alembic commands ###
