"""add base model

Revision ID: 1489b3b3c031
Revises: f488b2d46de4
Create Date: 2022-09-02 12:17:28.368258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1489b3b3c031'
down_revision = 'f488b2d46de4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_cards', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('health_cards', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('medias', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('medias', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('ownerships', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ownerships', 'deleted_at')
    op.drop_column('medias', 'deleted_at')
    op.drop_column('medias', 'updated_at')
    op.drop_column('health_cards', 'deleted_at')
    op.drop_column('health_cards', 'updated_at')
    # ### end Alembic commands ###
