"""add WALK to treatment type

Revision ID: 1_add_walk_treatment_type
Revises: 0783f250015e
Create Date: 2025-10-16 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1_add_walk_treatment_type'
down_revision = '0783f250015e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add new value to PostgreSQL enum type used by treatments.type
    # Assuming enum type name autogenerated as 'treatmenttype'
    op.execute("ALTER TYPE treatmenttype ADD VALUE IF NOT EXISTS 'WALK'")


def downgrade() -> None:
    # Enum value removals are not straightforward/portable.
    # To revert you would need to recreate the enum without 'WALK' and
    # update dependent columns. We document instead of implementing.
    raise RuntimeError("Downgrade not supported for adding enum value 'WALK'.")
