"""added duration

Revision ID: 1d0d61308ba8
Revises: 8a4adee6b782
Create Date: 2023-06-12 13:40:28.410501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0d61308ba8'
down_revision = '8a4adee6b782'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatments', sa.Column('duration', sa.Enum('TEN_MINUTES', 'QUARTER_HOUR', 'THREE_QUARTER', 'HALF_HOUR', 'HOUR_AND_HALF', 'TWO_HOURS', name='treatmentduration'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatments', 'duration')
    # ### end Alembic commands ###
