"""code metadata

Revision ID: 241e1ff99aff
Revises: 555944b84665
Create Date: 2024-09-12 11:50:41.756516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '241e1ff99aff'
down_revision = '555944b84665'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codes', 'meta_tags', schema='graph_a_pet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codes', sa.Column('meta_tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True), schema='graph_a_pet')
    # ### end Alembic commands ###
