"""create_view

Revision ID: 2507fc46c4b4
Revises: 241e1ff99aff
Create Date: 2024-09-17 09:31:30.178780

"""
from alembic import op
import sqlalchemy as sa
from repository.users.views import view_declaration, view_drop

# revision identifiers, used by Alembic.
revision = '2507fc46c4b4'
down_revision = '241e1ff99aff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(view_declaration)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(view_drop)
    # ### end Alembic commands ###
