"""added last_activity

Revision ID: 32d76f54e2d9
Revises: 22b9735a9d19
Create Date: 2022-11-21 10:52:26.447590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d76f54e2d9'
down_revision = '22b9735a9d19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_activity', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_activity')
    # ### end Alembic commands ###
