"""column restore_before and after to damnatio

Revision ID: 38e98d6ad9a0
Revises: 3fc9f4d2c0dd
Create Date: 2023-02-08 13:26:15.570918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38e98d6ad9a0'
down_revision = '3fc9f4d2c0dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('damnationes_memoriae', sa.Column('restore_before', sa.JSON(), nullable=True))
    op.add_column('damnationes_memoriae', sa.Column('restore_after', sa.JSON(), nullable=True))
    op.drop_column('damnationes_memoriae', 'linked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('damnationes_memoriae', sa.Column('linked', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('damnationes_memoriae', 'restore_after')
    op.drop_column('damnationes_memoriae', 'restore_before')
    # ### end Alembic commands ###
