"""add linked column to damnatio

Revision ID: 3fc9f4d2c0dd
Revises: 8b33f3f37d13
Create Date: 2023-02-07 17:05:19.564856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc9f4d2c0dd'
down_revision = '8b33f3f37d13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('damnationes_memoriae', sa.Column('linked', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('damnationes_memoriae', 'linked')
    # ### end Alembic commands ###
