"""add base model to treatments

Revision ID: 47008f15dfbc
Revises: 1489b3b3c031
Create Date: 2022-09-02 12:18:58.534656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47008f15dfbc'
down_revision = '1489b3b3c031'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('treatments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('treatments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatments', 'deleted_at')
    op.drop_column('treatments', 'updated_at')
    op.drop_column('treatments', 'created_at')
    # ### end Alembic commands ###
