"""code fk

Revision ID: 472f1ccb3aa6
Revises: 2507fc46c4b4
Create Date: 2024-11-25 15:16:29.026603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472f1ccb3aa6'
down_revision = '2507fc46c4b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codes', 'created_by', schema='graph_a_pet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codes', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True), schema='graph_a_pet')
    # ### end Alembic commands ###
