"""second try

Revision ID: 4825a71b7e18
Revises: ec63a7a5d0ba
Create Date: 2022-07-15 10:01:22.721521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4825a71b7e18'
down_revision = 'ec63a7a5d0ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatments', sa.Column('alias', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatments', 'alias')
    # ### end Alembic commands ###
