"""removed_date_from_walks

Revision ID: 4fdea312bb76
Revises: b84dc1ffcbc5
Create Date: 2025-10-16 16:07:10.429737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fdea312bb76'
down_revision = 'b84dc1ffcbc5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('walks', 'date', schema='graph_a_pet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('walks', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False), schema='graph_a_pet')
    # ### end Alembic commands ###
