"""code metadata

Revision ID: 555944b84665
Revises: 
Create Date: 2024-09-12 11:12:20.755245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555944b84665'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codes', sa.Column('meta_tags', sa.ARRAY(sa.String()), nullable=True), schema='graph_a_pet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codes', 'meta_tags', schema='graph_a_pet')
    # ### end Alembic commands ###
