"""major updates in table

Revision ID: 58387be24d4b
Revises: c9d0e1f2a3b4
Create Date: 2026-07-06 16:14:03.618860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58387be24d4b'
down_revision = 'c9d0e1f2a3b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
