"""add base model to coats

Revision ID: 588c5fcded79
Revises: 47008f15dfbc
Create Date: 2022-09-02 12:20:00.237610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588c5fcded79'
down_revision = '47008f15dfbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coats', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('coats', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coats', 'deleted_at')
    op.drop_column('coats', 'updated_at')
    # ### end Alembic commands ###
