"""changed json to jsonb

Revision ID: 58d4b039914b
Revises: 588c5fcded79
Create Date: 2022-09-06 14:13:09.740408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d4b039914b'
down_revision = '588c5fcded79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
