"""switching deleted content managment

Revision ID: 5f05355098d0
Revises: a4f0fe3e0e85
Create Date: 2023-02-06 09:35:49.211040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f05355098d0'
down_revision = 'a4f0fe3e0e85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('damnatio_memoriae',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('original_table', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('original_data',postgresql.JSONB, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('coats', 'deleted_at')
    op.drop_column('health_cards', 'deleted_at')
    op.drop_column('medias', 'deleted_at')
    op.drop_column('ownerships', 'deleted_at')
    op.drop_column('pet_bodies', 'deleted_at')
    op.drop_column('pets', 'deleted_at')
    op.drop_column('treatments', 'deleted_at')
    op.drop_column('users', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('treatments', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('pets', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('pet_bodies', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('ownerships', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('medias', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('health_cards', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('coats', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_table('damnatio_memoriae')
    # ### end Alembic commands ###
