"""added shelters

Revision ID: 639f4190c35e
Revises: f1dee6089991
Create Date: 2025-10-30 15:31:24.601844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639f4190c35e'
down_revision = 'f1dee6089991'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('street_number', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('province_code', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('contacts', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='graph_a_pet'
    )
    op.create_table('shelter_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('shelter_id', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'STAFF', 'VOLUNTEER', name='role'), nullable=True),
    sa.ForeignKeyConstraint(['shelter_id'], ['graph_a_pet.shelters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['graph_a_pet.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='graph_a_pet'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelter_roles', schema='graph_a_pet')
    op.drop_table('shelters', schema='graph_a_pet')
    # ### end Alembic commands ###
