"""place

Revision ID: 6f6904eb14ce
Revises: f0526d5f4620
Create Date: 2023-02-20 12:22:06.107026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f6904eb14ce'
down_revision = 'f0526d5f4620'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('place', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'place')
    # ### end Alembic commands ###
