"""added main color to media

Revision ID: 721fdbae2093
Revises: fa2e8943f745
Create Date: 2023-05-02 15:18:38.589788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721fdbae2093'
down_revision = 'fa2e8943f745'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medias', sa.Column('main_color', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medias', 'main_color')
    # ### end Alembic commands ###
