"""deleted user_id

Revision ID: 75a4ce9a3356
Revises: d23343c32666
Create Date: 2023-02-21 08:54:08.080888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a4ce9a3356'
down_revision = 'd23343c32666'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reports_user_id_fkey', 'reports', type_='foreignkey')
    op.drop_column('reports', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('reports_user_id_fkey', 'reports', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
