"""added created by to codes

Revision ID: 8a4adee6b782
Revises: 9224b570d09c
Create Date: 2023-05-24 12:25:50.854224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4adee6b782'
down_revision = '9224b570d09c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
