"""rename damnationes memoriae

Revision ID: 8b33f3f37d13
Revises: 5f05355098d0
Create Date: 2023-02-06 13:22:34.260540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b33f3f37d13'
down_revision = '5f05355098d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('damnationes_memoriae',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('original_table', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('original_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('damnatio_memoriae')
    op.drop_column('statistics', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_table('damnatio_memoriae',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('original_table', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('original_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='damnatio_memoriae_pkey')
    )
    op.drop_table('damnationes_memoriae')
    # ### end Alembic commands ###
