"""column updated_at to ownerships

Revision ID: 8d50eb53befd
Revises: a41735fc3e15
Create Date: 2022-09-02 10:04:42.798300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d50eb53befd'
down_revision = 'a41735fc3e15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ownerships', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ownerships', 'updated_at')
    # ### end Alembic commands ###
