"""deleted at at statistics

Revision ID: 9cbc11c99434
Revises: 0c75407692b4
Create Date: 2022-11-25 14:19:12.462168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cbc11c99434'
down_revision = '0c75407692b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistics', 'deleted_at')
    # ### end Alembic commands ###
