"""Added account table

Revision ID: a1265b755629
Revises: ff0efc88e709
Create Date: 2022-08-01 15:05:14.292702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1265b755629'
down_revision = 'ff0efc88e709'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
