"""added column updated at to user

Revision ID: a41735fc3e15
Revises: a45fddb0a8cf
Create Date: 2022-09-01 12:01:50.019254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41735fc3e15'
down_revision = 'a45fddb0a8cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatments', 'updated_at')
    # ### end Alembic commands ###
