"""code fk_2

Revision ID: aa8a9806ac81
Revises: 472f1ccb3aa6
Create Date: 2024-11-25 15:17:41.036077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa8a9806ac81'
down_revision = '472f1ccb3aa6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
