"""added 2 column to code table

Revision ID: b7cf57563308
Revises: 1d0d61308ba8
Create Date: 2024-05-09 12:14:24.545037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7cf57563308'
down_revision = '1d0d61308ba8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codes', sa.Column('scope', sa.String(), nullable=True))
    op.add_column('codes', sa.Column('valid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codes', 'valid')
    op.drop_column('codes', 'scope')
    # ### end Alembic commands ###
