"""created Walks table

Revision ID: b84dc1ffcbc5
Revises: 1_add_walk_treatment_type
Create Date: 2025-10-16 11:54:59.872949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84dc1ffcbc5'
down_revision = '1_add_walk_treatment_type'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('treatment_id', sa.String(), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('leash_pulling_rating', sa.Integer(), nullable=True),
    sa.Column('behavior_rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['treatment_id'], ['graph_a_pet.treatments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='graph_a_pet'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walks', schema='graph_a_pet')
    # ### end Alembic commands ###
