"""name

Revision ID: d23343c32666
Revises: 6f6904eb14ce
Create Date: 2023-02-20 13:22:01.049174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd23343c32666'
down_revision = '6f6904eb14ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=8, scale=6), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('type', sa.Enum('MISSING', 'FOUND', name='reporttypes'), nullable=True),
    sa.Column('notes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('pet_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('responders', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('reporter', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('report')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(precision=8, scale=6), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('MISSING', 'FOUND', name='reporttype'), autoincrement=False, nullable=True),
    sa.Column('notes', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('pet_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('responders', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True),
    sa.Column('reporter', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('place', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name='report_pet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='report_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='report_pkey')
    )
    op.drop_table('reports')
    # ### end Alembic commands ###
