"""walk_ratings

Revision ID: d3f7fa62c886
Revises: 97f752160198
Create Date: 2026-06-02 23:04:15.982509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3f7fa62c886'
down_revision = '97f752160198'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walk_ratings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('walk_id', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('OVERALL', 'LEASH_PULLING', 'BEHAVIOR', 'AGGRESSION', 'CALM', name='walkratingtype'), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['walk_id'], ['walks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('walks', 'overall_rating')
    op.drop_column('walks', 'leash_pulling_rating')
    op.drop_column('walks', 'behavior_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('walks', sa.Column('behavior_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('walks', sa.Column('leash_pulling_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('walks', sa.Column('overall_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('walk_ratings')
    # ### end Alembic commands ###
