"""changed column type

Revision ID: e17c48219554
Revises: 39cbe8abeb10
Create Date: 2023-02-10 14:17:27.292231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17c48219554'
down_revision = '39cbe8abeb10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
