"""edited reports columns

Revision ID: f0526d5f4620
Revises: d768490c0eb1
Create Date: 2023-02-20 11:09:13.330027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0526d5f4620'
down_revision = 'd768490c0eb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('responders', sa.ARRAY(sa.JSON()), nullable=True))
    op.add_column('report', sa.Column('reporter', sa.JSON(), nullable=True))
    op.drop_column('report', 'reporters')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('reporters', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=True))
    op.drop_column('report', 'reporter')
    op.drop_column('report', 'responders')
    # ### end Alembic commands ###
