"""added cure table

Revision ID: f1dee6089991
Revises: 4fdea312bb76
Create Date: 2025-10-28 16:43:32.079531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1dee6089991'
down_revision = '4fdea312bb76'
branch_labels = None
depends_on = None

# Reuse existing PostgreSQL enum type (already created in a previous migration)
frequency_unit_enum = postgresql.ENUM(
    'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY',
    name='frequencyunit',
    create_type=False  # Do not (re)create the type
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cures',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('treatment_id', sa.String(), nullable=True),
        sa.Column('frequency_value', sa.Integer(), nullable=True),
        sa.Column('frequency_unit', frequency_unit_enum, nullable=True),
        sa.Column('frequency_times', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['treatment_id'], ['graph_a_pet.treatments.id']),
        sa.PrimaryKeyConstraint('id'),
        schema='graph_a_pet'
    )
    op.drop_column('treatments', 'frequency_unit', schema='graph_a_pet')
    op.drop_column('treatments', 'frequency_value', schema='graph_a_pet')
    op.drop_column('treatments', 'frequency_times', schema='graph_a_pet')
    op.drop_column('walks', 'notes', schema='graph_a_pet')
    # ### end Alembic commands ###
    op.execute("ALTER TYPE treatmenttype ADD VALUE IF NOT EXISTS 'CURE'")

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('walks', sa.Column('notes', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True), schema='graph_a_pet')
    op.add_column('treatments', sa.Column('frequency_times', sa.INTEGER(), autoincrement=False, nullable=True), schema='graph_a_pet')
    op.add_column('treatments', sa.Column('frequency_value', sa.INTEGER(), autoincrement=False, nullable=True), schema='graph_a_pet')
    op.add_column('treatments', sa.Column('frequency_unit', frequency_unit_enum, autoincrement=False, nullable=True), schema='graph_a_pet')
    op.drop_table('cures', schema='graph_a_pet')
    # ### end Alembic commands ###