"""try base model

Revision ID: f488b2d46de4
Revises: 8d50eb53befd
Create Date: 2022-09-02 12:16:03.891496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f488b2d46de4'
down_revision = '8d50eb53befd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet_bodies', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('pet_bodies', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('pets', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('pets', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('treatments', 'updated_at')
    op.drop_column('treatments', 'created_at')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.add_column('treatments', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('treatments', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('pets', 'deleted_at')
    op.drop_column('pets', 'updated_at')
    op.drop_column('pet_bodies', 'deleted_at')
    op.drop_column('pet_bodies', 'updated_at')
    # ### end Alembic commands ###
