"""removed coats table

Revision ID: f676da2034f6
Revises: aa8a9806ac81
Create Date: 2024-11-26 09:29:34.397088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f676da2034f6'
down_revision = 'aa8a9806ac81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the foreign key constraint before dropping the table
    op.drop_constraint('pet_bodies_coat_id_fkey', 'pet_bodies', type_='foreignkey', schema='graph_a_pet')
    
    # Drop the `coats` table
    op.drop_table('coats', schema='graph_a_pet')

    # Add the new `coat_length` column
    op.add_column('pet_bodies', sa.Column('coat_length', sa.Enum('SHORT', 'MEDIUM', 'LENGHT', 'HAIRLESS', name='coatlength'), nullable=True), schema='graph_a_pet')

    # Drop the `coat_id` column
    op.drop_column('pet_bodies', 'coat_id', schema='graph_a_pet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Re-add the `coat_id` column
    op.add_column('pet_bodies', sa.Column('coat_id', sa.VARCHAR(), autoincrement=False, nullable=True), schema='graph_a_pet')

    # Drop the `coat_length` column
    op.drop_column('pet_bodies', 'coat_length', schema='graph_a_pet')

    # Recreate the `coats` table
    op.create_table('coats',
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('colors', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
        sa.Column('length', postgresql.ENUM('SHORT', 'MEDIUM', 'LENGHT', 'HAIRLESS', name='coatlength'), autoincrement=False, nullable=True),
        sa.Column('pattern', postgresql.ENUM('MERLE', 'BRINDLE', 'HARLEQUIN', 'TICKED', 'SPOTTED', 'ROAN', 'TRICOLOR', 'BICOLOR', 'SOLID', 'COLORPOINT', name='coatpattern'), autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='coats_pkey'),
        schema='graph_a_pet'
    )

    # Recreate the foreign key constraint
    op.create_foreign_key('pet_bodies_coat_id_fkey', 'pet_bodies', 'coats', ['coat_id'], ['id'], schema='graph_a_pet')
    # ### end Alembic commands ###
