from .users.models import *
from .pets.models import *
from .ownerships.models import * 
from .health_cards.models import *
from .treatments.models import *
from .medias.models import *
from .statistics.models import *
from .damnationes_memoriae.models import *
from .reports.models import *
from .codes.models import * 
from .walks.models import *
from .walk_ratings.models import *
from .cures.models import *
from .shelters.models import *
from .shelter_roles.models import *
from .shelter_pets.models import *
from .shelter_tasks.models import *
from .shelter_walks.models import *
from .shelter_walk_ratings.models import *
from .shelter_maps.models import *
from .shelter_areas.models import *
from .shelter_boxes.models import *
from .shelter_box_occupancies.models import *
from .shelter_map_elements.models import *
from .shelter_inventory_items.models import *
from .shelter_inventory_movements.models import *
from .shelter_claim_requests.models import *
from .pet_weights.models import *