from .coats.models import * 
from .pet_bodies.models import * 
from .users.models import *
from .pets.models import *
from .ownerships.models import * 
from .health_cards.models import *
from .treatments.models import *
from .medias.models import *
from .statistics.models import *
from .damnationes_memoriae.models import *
from .reports.models import *